version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node
        steps:
            - run:
                  name: WebPageTest
                  command: |
                      curl "https://api.speedcurve.com/v1/deploys" -u 6spP6RTwq9UmAPYCQd8aPx8ULhjtGx:Gvin#ind1452 --request POST --data site_id=330232 --data-urlencode "note=#${CIRCLE_BUILD_NUM}" —data-urlencode "detail=${CIRCLE_BUILD_URL}"
