version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node
        steps:
            - run: curl "https://api.speedcurve.com/v1/deploys" -uei3pq3j1dmvp9g9by31brfz8b68tek:Gvin#ind1452 --request POST --data site_id=330796 --data-urlencode "note=#${CIRCLE_BUILD_NUM}" --data-urlencode "detail=${CIRCLE_BUILD_URL}"