version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node
        steps:
            - run: curl "https://api.speedcurve.com/v1/deploys" -u7hwtz697y7voso3et6byzx8dqc33qs:Gvin#ind1452 --request POST --data site_id=330232 --data-urlencode "note=#${CIRCLE_BUILD_NUM}" --data-urlencode "detail=${CIRCLE_BUILD_URL}"